#!/usr/bin/env bash
# This is a script that displays content of file etc/passwd
file="/etc/passwd"
while IFS= read -r line
do
	USERNAME=$(echo "$line" | cut -d ":" -f1)
	GROUP_ID=$(echo "$line" | cut -d ":" -f4)
	HOME_DIRECTORY=$(echo "$line" | cut -d ":" -f6)
	C_SHELL=$(echo "$line" | cut -d ":" -f7)
	USER_ID=$(echo "$line" | cut -d ":" -f3)
	PASSWRD=$(echo "$line" | cut -d ":" -f2)
	UID_INFO=$(echo "$line" | cut -d ':' -f5)
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $C_SHELL. $USER_ID's place is protected by the passcode $PASSWRD, more info about the user here: $UID_INFO"
done < "$file"
