#!/usr/bin/env bash
# This is a script that displays the visitor IP along
# with the HTTP status code from the Apache log file.
file=./apache-access.log
if [[ -e "$file" ]]; then
  tee<$file | awk '{print $1 " " $9}'
fi