#!/usr/bin/env bash
# This script is print the line "Holberton School" 10 times
count=1
while [[ $count -le 20 ]];
  do
    echo "$count"
    case $count in
	  4)
	    echo "bad luck from China"
	    ;;
	  9)
	    echo "bad luck from Japan"
	    ;;
	  17)
	    echo "bad luck from Italy"
	    ;;
    esac
    count=$((count+1))
  done