#!/usr/bin/env bash
# This script is print the line "Holberton School" 10 times
file=./holbertonschool
if [[ -e "$file" ]]; then
  echo "holbertonschool file exists"
  if [[ -s "$file" ]]; then
    echo "holbertonschool file is not empty"
  else
    echo "holbertonschool file is empty"
  fi
  if [[ -f "$file" ]]; then
    echo "holbertonschool is a regular file"
  fi
else
  echo "holbertonschool file does not exist"
fi